port: 5600
globalExceptionFilter: true
database:
  mongo:
    url: sensitive
routing:
  base: "api"
jsonLimit: 2mb
middlewares:
  cors:
    activate: true
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - "Content-Type"
      - "Authorization"
